import fs from 'fs';
let content = fs.readFileSync('src/Page/BusTickets.jsx', 'utf8');
content = content.replace("                        style={{ width: \"100%\", padding: \"10px 12px\", borderRadius: 8, border: \"1px solid #ddd\", fontSize: 14 }} />\n                    </div>\n                    <div>\n                      <label style={{ display: \"block\", fontSize: 13, fontWeight: 600, marginBottom: 6 }}>{t.nationality}</label>", 
"                        <input\n                          value={passengerInfo[f.key]}\n                          onChange={e => setPassengerInfo(p => ({...p, [f.key]: toLatinUpper(e.target.value)}))}\n                          style={{ width: \"100%\", padding: \"10px 12px\", borderRadius: 8, border: \"1px solid #ddd\", fontSize: 14, letterSpacing: 1 }} />\n                      </div>\n                    ))}\n                    <div>\n                      <label style={{ display: \"block\", fontSize: 13, fontWeight: 600, marginBottom: 6 }}>{t.dob}</label>\n                      <input\n                        value={passengerInfo.dob}\n                        onChange={e => setPassengerInfo(p => ({...p, dob: formatDob(e.target.value)}))}\n                        placeholder=\"__/__/____\"\n                        inputMode=\"numeric\"\n                        maxLength={10}\n                        style={{ width: \"100%\", padding: \"10px 12px\", borderRadius: 8, border: \"1px solid #ddd\", fontSize: 14, letterSpacing: 2 }}\n                      />\n                    </div>\n                    <div>\n                      <label style={{ display: \"block\", fontSize: 13, fontWeight: 600, marginBottom: 6 }}>{t.nationality}</label>");

content = content.replace("                        style={{ width: \"100%\", padding: \"10px 12px\", borderRadius: 8, border: \"1px solid #ddd\", fontSize: 14 }} />\r\n                    </div>\r\n                    <div>\r\n                      <label style={{ display: \"block\", fontSize: 13, fontWeight: 600, marginBottom: 6 }}>{t.nationality}</label>", 
"                        <input\r\n                          value={passengerInfo[f.key]}\r\n                          onChange={e => setPassengerInfo(p => ({...p, [f.key]: toLatinUpper(e.target.value)}))}\r\n                          style={{ width: \"100%\", padding: \"10px 12px\", borderRadius: 8, border: \"1px solid #ddd\", fontSize: 14, letterSpacing: 1 }} />\r\n                      </div>\r\n                    ))}\r\n                    <div>\r\n                      <label style={{ display: \"block\", fontSize: 13, fontWeight: 600, marginBottom: 6 }}>{t.dob}</label>\r\n                      <input\r\n                        value={passengerInfo.dob}\r\n                        onChange={e => setPassengerInfo(p => ({...p, dob: formatDob(e.target.value)}))}\r\n                        placeholder=\"__/__/____\"\r\n                        inputMode=\"numeric\"\r\n                        maxLength={10}\r\n                        style={{ width: \"100%\", padding: \"10px 12px\", borderRadius: 8, border: \"1px solid #ddd\", fontSize: 14, letterSpacing: 2 }}\r\n                      />\r\n                    </div>\r\n                    <div>\r\n                      <label style={{ display: \"block\", fontSize: 13, fontWeight: 600, marginBottom: 6 }}>{t.nationality}</label>");

fs.writeFileSync('src/Page/BusTickets.jsx', content);
console.log("BusTickets.jsx fixed via regex script successfully");
